"""empty message

Revision ID: e65c1ddf6572
Revises: 
Create Date: 2025-11-04 18:15:51.159834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65c1ddf6572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_name', sa.String(length=100), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constellation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constellation_name', sa.String(length=100), nullable=False),
    sa.Column('satellite_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('constellation_id', sa.Integer(), nullable=False),
    sa.Column('info_line1', sa.Text(), nullable=False),
    sa.Column('info_line2', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'constellation_id', name='unique_satellite_in_constellation')
    )
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satellite_satellite_id'), ['satellite_id'], unique=False)

    op.create_table('linked_satellite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id1', sa.Integer(), nullable=False),
    sa.Column('satellite_id2', sa.Integer(), nullable=False),
    sa.Column('constellation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satellite_id1', 'constellation_id'], ['satellite.satellite_id', 'satellite.constellation_id'], name='fk_linked_sat1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satellite_id2', 'constellation_id'], ['satellite.satellite_id', 'satellite.constellation_id'], name='fk_linked_sat2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constellation_id', 'satellite_id1', 'satellite_id2', name='unique_link_forward'),
    sa.UniqueConstraint('constellation_id', 'satellite_id2', 'satellite_id1', name='unique_link_backward')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_satellite')
    with op.batch_alter_table('satellite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satellite_satellite_id'))

    op.drop_table('satellite')
    op.drop_table('constellation')
    op.drop_table('base')
    op.drop_table('user')
    # ### end Alembic commands ###
